---
- name: "Approve Install Plans"
  hosts: clusters
  connection: local
  gather_facts: false
# vars:
#   kubeconfig_path: FROM HOST
#   username: FROM HOST
  vars_files:
    - vars.yml
  tasks:
    - name: "Approve Install Plans"
      ansible.builtin.include_tasks:
        file: "tasks/approve_install_plans.yml"
