---
- name: "README"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    readme: |
      This playbook simply imports multiple playbooks to spin up a demo environment.
      To start this playbook, you will need an aws account with a preconfigured route53 entry and you need to update vars.yml.
      At the end of the playbook, you should have two clusters in an "ingress mesh" configuration.
      To run the full playbook, use the "AWS_PROFILE" variable alongside your playbook command:
        ex. AWS_PROFILE=example ansible-playbook demo.yml
      To run any playbook by itself, you can simply use "--tags \{\{ playbook_name \}\}".
      Playbooks:
        - bootstrap_aws_network.yml (--tags bootstrap_aws_network)
        - install_openshift.yml (--tags install_openshift)
        - bootstrap_aws_resources.yml (--tags bootstrap_aws_resources)
        - approve_certificates.yml (--tags approve_certificates.yml)
        - deploy_argo_apps.yml (--tags deploy_argo_apps)
        - approve_install_plans.yml (--tags approve_install_plans)
        - deploy_rhsi_tokens.yml (--tags deploy_rhsi_tokens)

  tasks:
    - name: "README"
      ansible.builtin.debug:
        msg: "{{ readme.split('\n') }}"

    - name: "REQUIRED ENV - AWS_PROFILE"
      when: "not lookup('ansible.builtin.env', 'AWS_PROFILE')"
      ansible.builtin.fail:
        msg: "'AWS_PROFILE' is a required environment variable. Specify via: 'AWS_PROFILE=sandboxXYZ ansible-playbook ...'"

- name: "Bootstrap AWS (tag: bootstrap_aws_network)"
  tags: "bootstrap_aws_network"
  ansible.builtin.import_playbook: "bootstrap_aws_network.yml"

- name: "Deploy OCP Clusters (tag: install_openshift)"
  tags: "install_openshift"
  ansible.builtin.import_playbook: "install_openshift.yml"

- name: "Bootstrap AWS Resources (tag: bootstrap_aws_resources)"
  tags: "bootstrap_aws_resources"
  ansible.builtin.import_playbook: "bootstrap_aws_resources.yml"

- name: "Approve Certificate Signing Requests (tag: approve_certificates)"
  tags: "approve_certificates"
  ansible.builtin.import_playbook: "approve_certificates.yml"

- name: "Deploy Argo Apps (tag: deploy_argo_apps)"
  tags: "deploy_argo_apps"
  ansible.builtin.import_playbook: "deploy_argo_apps.yml"

- name: "Approve Install Plans (tag: approve_install_plans)"
  tags: "approve_install_plans"
  ansible.builtin.import_playbook: "approve_install_plans.yml"

- name: "Deploy RHSI Tokens (tag: deploy_rhsi_tokens)"
  tags: "deploy_rhsi_tokens"
  ansible.builtin.import_playbook: "deploy_rhsi_tokens.yml"
