---
- name: Deploy Argo Apps
  hosts: clusters
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: "Create Argo Directory"
      ansible.builtin.file:
        state: directory
        path: "{{ argo_path }}"
        mode: "0755"

    - name: "Create ApplicationSet Manifest"
      ansible.builtin.template:
        src: "appset.argo.yml.j2"
        mode: "u=rw,g=r,o=r"
        dest: "{{ argo_path }}/appset.ingressmesh.yml"

    - name: "Ensure OpenShift GitOps (Argo) is Available"
      register: res_argo
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        username: "{{ username }}"
        state: present
        src: "../../hunt/openshift-gitops-operator.yml"

    - name: "Pause for OpenShift GitOps to be ready (simple 60 second pause)" # noqa: no-handler
      when: res_argo.changed
      ansible.builtin.pause:
        seconds: 60

    - name: "Deploy the ApplicationSet"
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        username: "{{ username }}"
        state: present
        apply: true
        src: "{{ argo_path }}/appset.ingressmesh.yml"

    - name: "Allow A Brief Pause For Argo To Init Apps"
      ansible.builtin.pause:
        seconds: 60
