---
- name: Deploy Argo Apps
  gather_facts: false
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  vars:
    git_repo_url: "https://github.com/rerickso-at-redhat/ocp_ingress"
    git_repo_revision: "main"
    argo_manifests:
      - "app.metallb.yml"
      - "app.gatewayapi.yml"
      - "app.rhsi.yml"
      - "app.app1.yml"
      - "app.app2.yml"
    argo_values:
      - name: alpha
        argo_path: "{{ clusters[0].argo_path }}"
        metallb:
          metallb:
            ipaddresspool:
              name: "anycast-address-pool"
              addresses:
                - "{{ supernet_anycast }}"
            bgppeers:
              - name: "alpha-us-east-2a"
                myASN: 65001
                peerASN: 65000
                peerAddress: 10.1.0.96
        gatewayapi:
          gatewayapi:
            namespace: "anycast-gateways"
            # NOTE: Very limited customization scope - extend template to fully use gatewayapi
            gateways:
              - namespace: "anycast-gateways"
                name: "anycast-gateway-shared"
                ipaddress: "10.255.255.1"
                hostname: "anycast.{{ sandbox_domain }}"
              - namespace: "anycast-gateways"
                name: "anycast-gateway-dedicated-app1"
                ipaddress: "10.255.255.11"
                hostname: "app1-anycast.{{ sandbox_domain }}"
        rhsi:
          rhsi:
            subscription:
              channel: "stable-2"
      - name: beta
        argo_path: "{{ clusters[1].argo_path }}"
        metallb:
          metallb:
            ipaddresspool:
              name: "anycast-address-pool"
              addresses:
                - "{{ supernet_anycast }}"
            bgppeers:
              - name: "beta-us-east-2a"
                myASN: 65002
                peerASN: 65000
                peerAddress: 10.2.0.96
        gatewayapi:
          gatewayapi:
            namespace: "anycast-gateways"
            # NOTE: Very limited customization scope - extend template to fully use gatewayapi
            gateways:
              - namespace: "anycast-gateways"
                name: "anycast-gateway-shared"
                ipaddress: "10.255.255.1"
                hostname: "anycast.{{ sandbox_domain }}"
              - namespace: "anycast-gateways"
                name: "anycast-gateway-dedicated-app2"
                ipaddress: "10.255.255.12"
                hostname: "app2-anycast.{{ sandbox_domain }}"
        rhsi:
          rhsi:
            subscription:
              channel: "stable-2"
  tasks:
    - name: "Create Directories For Each Cluster"
      loop: "{{ clusters }}"
      ansible.builtin.file:
        state: directory
        path: "{{ item.argo_path }}"
        mode: "0755"

    # MetalLB
    - name: "Create Argo Application Manifests - {{ app_name }}"
      loop: "{{ argo_values }}"
      vars:
        app_name: "metallb"
        chart_name: "metallb"
        values_object: "{{ item.metallb }}"
      ansible.builtin.template:
        src: "app.argo.yml.j2"
        mode: "u=rw,g=r,o=r"
        dest: "{{ item.argo_path }}/app.{{ app_name }}.yml"

    # Gateway API
    - name: "Create Argo Application Manifests - {{ app_name }}"
      loop: "{{ argo_values }}"
      vars:
        app_name: "gatewayapi"
        chart_name: "gatewayapi"
        values_object: "{{ item.gatewayapi }}"
      ansible.builtin.template:
        src: "app.argo.yml.j2"
        mode: "u=rw,g=r,o=r"
        dest: "{{ item.argo_path }}/app.{{ app_name }}.yml"

    # RHSI
    - name: "Create Argo Application Manifests - {{ app_name }}"
      loop: "{{ argo_values }}"
      vars:
        app_name: "rhsi"
        chart_name: "rhsi"
        values_object: "{{ item.rhsi }}"
      ansible.builtin.template:
        src: "app.argo.yml.j2"
        mode: "u=rw,g=r,o=r"
        dest: "{{ item.argo_path }}/app.{{ app_name }}.yml"

    # APP 1
    - name: "Create Argo Application Manifests - {{ app_name }}"
      loop:
        - argo_path: "{{ clusters[0].argo_path }}"
          local: true
        - argo_path: "{{ clusters[1].argo_path }}"
          local: false
      vars:
        app_name: "app1"
        chart_name: "app"
        values_object:
          app:
            local: "{{ item.local }}"
            namespace: app1
            name: app1
            route:
              host: "app1.apps.alpha.{{ sandbox_domain }}"
            httproute:
              port: 8080
      ansible.builtin.template:
        src: "app.argo.yml.j2"
        mode: "u=rw,g=r,o=r"
        dest: "{{ item.argo_path }}/app.{{ app_name }}.yml"

    # APP 2
    - name: "Create Argo Application Manifests - {{ app_name }}"
      loop:
        - argo_path: "{{ clusters[0].argo_path }}"
          local: false
        - argo_path: "{{ clusters[1].argo_path }}"
          local: true
      vars:
        app_name: "app2"
        chart_name: "app"
        values_object:
          app:
            local: "{{ item.local }}"
            namespace: app2
            name: app2
            route:
              host: "app2.apps.beta.{{ sandbox_domain }}"
            httproute:
              port: 8080
      ansible.builtin.template:
        src: "app.argo.yml.j2"
        mode: "u=rw,g=r,o=r"
        dest: "{{ item.argo_path }}/app.{{ app_name }}.yml"

    - name: "Ensure OpenShift GitOps (Argo) is Available"
      register: res_argo
      loop: "{{ clusters }}"
      kubernetes.core.k8s:
        kubeconfig: "{{ item.kubeconfig_path }}"
        username: "{{ item.username }}"
        state: present
        src: "../../hunt/openshift-gitops-operator.yml"

    - name: "Pause for OpenShift GitOps to be ready (simple 60 second pause)" # noqa: no-handler
      when: res_argo.changed
      ansible.builtin.pause:
        seconds: 60

    - name: "Deploy the Argo App Templates - alpha"
      loop: "{{ argo_manifests }}"
      vars:
        cluster: "{{ clusters[0] }}"
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig_path }}"
        username: "{{ cluster.username }}"
        state: present
        src: "{{ cluster.argo_path }}/{{ item }}"

    - name: "Deploy the Argo App Templates - beta"
      loop: "{{ argo_manifests }}"
      vars:
        cluster: "{{ clusters[1] }}"
      kubernetes.core.k8s:
        kubeconfig: "{{ cluster.kubeconfig_path }}"
        username: "{{ cluster.username }}"
        state: present
        src: "{{ cluster.argo_path }}/{{ item }}"

    - name: "Allow A Brief Pause For Argo To Init Apps"
      ansible.builtin.pause:
        seconds: 60
