---
- name: "Deploy BGP Router and BGP Interfaces"
  hosts: localhost
  gather_facts: false
  vars_files:
    - "vars.yml"
    - "generated_facts.yml"
  collections:
    - custom_aws.ec2
  tasks:
    - name: Initialize The Demo SSH Key 
      amazon.aws.ec2_key:
        name: key-aws-demo
      register: res_key

    - name: Create The Demo SSH Key Locally
      when: "res_key.key.private_key is defined"
      ansible.builtin.copy:
        mode: "0600"
        content: "{{ res_key.key.private_key }}"
        dest: "secrets/key-aws-demo.pem"

    - name: Initialize Bastion EC2 Instance
      register: res_bastion
      amazon.aws.ec2_instance:
        name: "bastion"
        key_name: "key-aws-demo"
        vpc_subnet_id: "{{ tor_public_subnet_ids[3] }}" # NOTE: hardcoded index
        instance_type: "t2.small"
        security_group: "public-facing-vms"
        image_id: "{{ ami_rhel_10 }}"
        network_interfaces:
          - assign_public_ip: true

    - name: "Create A Security Group For BGP Peering (tor-side)"
      amazon.aws.ec2_security_group:
        name: "tor-bgp-peering"
        description: "TOR-side BGP Peering"
        vpc_id: "{{ res_vpcs.results[0].vpc.id  }}"
        rules:
          - proto: tcp
            ports: 22 
            cidr_ip: "{{ supernet_clusters }}"
          - proto: tcp
            ports: 179 # BGP
            cidr_ip: "{{ supernet_alpha }}"
          - proto: udp
            ports:
              - 3784 # BFD
              - 3785 # BFD
            cidr_ip: "{{ supernet_alpha }}"
          - proto: tcp
            ports: 179 # BGP
            cidr_ip: "{{ supernet_beta }}"
          - proto: udp
            ports:
              - 3784 # BFD
              - 3785 # BFD
            cidr_ip: "{{ supernet_beta }}"
 
    # NOTE: assumes a very specific formatting of the subnet_reservations variable passed from bootstrapping
    - name: "Create Network Interfaces For TOR Subnet IPv4 Reservations"
      register: res_eni_tor
      loop: "{{ subnet_reservations }}"
      when: "item.cluster in ['tor']"
      amazon.aws.ec2_eni:
        private_ip_address: "{{ item.cidr.split('/')[0] }}"
        subnet_id: "{{ item.subnet_id }}"
        security_groups:
          - "tor-bgp-peering"
        tags:
          Name: "{{ item.eni_name }}"

    - name: "Get Security Groups"
      register: res_security_groups
      amazon.aws.ec2_security_group_info:
 
    # NOTE: assumes a very specific formatting of the subnet_reservations variable passed from bootstrapping
    - name: "Create Network Interfaces For Alpha/Beta Subnet IPv4 Reservations"
      register: res_eni_clusters
      loop: "{{ subnet_reservations }}"
      when: "item.cluster in ['alpha', 'beta']"
      amazon.aws.ec2_eni:
        private_ip_address: "{{ item.cidr.split('/')[0] }}"
        subnet_id: "{{ item.subnet_id }}"
        security_groups: 
          - "{{ res_security_groups.security_groups | selectattr('group_name', 'match', item.cluster + '-.*-node') | map(attribute='group_name') | first }}"
        tags:
          Name: "{{ item.eni_name }}"

    - name: "Get EC2 Instances"
      register: res_ec2_instances
      amazon.aws.ec2_instance_info:

    - set_fact:
        worker_instances: "{{ res_ec2_instances.instances | selectattr('tags.Name', 'match', '.*-worker-.*') }}"

    - name: "Assign A Secondary Interface For BGP Peering To Each Cluster Worker Node"
      loop: "{{ worker_instances }}"
      vars:
        netid: "{{ ((res_eni_tor | combine(res_eni_clusters)).results | selectattr('interface', 'defined') | selectattr('interface.subnet_id', 'equalto', item.subnet_id) | first).interface.id }}"
        intid: "{{ item.instance_id }}"
      changed_when: true
      failed_when: false
      command:
        cmd: "aws ec2 attach-network-interface --network-interface-id '{{ netid }}' --instance-id '{{ intid }}' --device-index '1' --network-card-index '0'"

    - name: "Edit Existing '-node-' Security Groups For BGP (tcp 179)"
      loop: "{{ res_security_groups.security_groups | selectattr('group_name', 'match', '.*-node') }}"
      amazon.aws.ec2_security_group:
        name: "{{ item.group_name }}"
        description: "{{ item.description }}"
        vpc_id: "{{ item.vpc_id }}"
        purge_rules: false
        purge_rules_egress: false
        purge_tags: false
        rules:
          - proto: tcp
            ports: 179
            cidr_ip: "{{ supernet_tor }}"
          - proto: udp
            ports:
              - 3784 # BFD
              - 3785 # BFD
            cidr_ip: "{{ supernet_tor }}"

    - name: Initialize the bgp-router ec2 instance
      register: ec2_router_bgp
      amazon.aws.ec2_instance:
        name: "router-bgp-test"
        key_name: "key-aws-demo"
        vpc_subnet_id: "{{ tor_private_subnet_ids[0] }}"
        instance_type: "t2.medium"
        image_id: "{{ ami_rhel_10 }}"
        #network_interfaces:
        #  - assign_public_ip: true
        #    groups:
        #      - "public-facing-vms"
        network_interfaces_ids:
          # The first three are the tor interfaces, the next 6 are the alpha/beta interfaces
          - id: "{{ res_eni_tor.results[0].interface.id }}"
            device_index: 0
        #  - id: "{{ res_eni_tor.results[1].interface.id }}"
        #    device_index: 1
        #  - id: "{{ res_eni_tor.results[2].interface.id }}"
        #    device_index: 2
          #- subnet_id: "{{ alpha_private_subnet_ids[0] }}"
          #  private_ip_addresses:
          #    - primary: false
          #      private_ip_address: 10.0.0.96

    - name: "Debug router-bgp Result When Requested (-vv)"
      ansible.builtin.debug:
        var: ec2_router_bgp
        verbosity: 2

    # TODO: the instances must be running to have a public IP available to add the host ... 
    - name: "Add the Test AWS hosts to the Ansible Inventory"
      ansible.builtin.add_host:
        hostname: "bastion"
        groups:
          - "test_vms"
        ansible_ssh_host: "{{ res_bastion.instances[0].network_interfaces[0].public_dns_name | default(false) or res_bastion.instances[0].network_interfaces[0].association.public_dns_name }}"
        ansible_ssh_port: 22
        ansible_host_key_checking: false
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "key-aws-demo.pem"
        public_ip_address: "{{ res_bastion.instances[0].network_interfaces[0].public_ip_address | default(false) or res_bastion.instances[0].network_interfaces[0].association.public_ip }}"

    - debug:
        var: ec2_router_bgp.instances[0]

    - debug:
        var: vars.hostvars

    # TODO: copy the key over to the bastion
    - name: "Add the BGP AWS host to the Ansible Inventory"
      ansible.builtin.add_host:
        hostname: "bgp-router"
        groups:
          - "bgp"
        ansible_ssh_host: "{{ ec2_router_bgp.instances[0].network_interfaces[0].private_ip_address }}"
        ansible_ssh_port: 22
        ansible_host_key_checking: false
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "key-aws-demo.pem"
        aws_private_dns_name: "{{ ec2_router_bgp.instances[0].network_interfaces[0].private_dns_name }}"
        ansible_ssh_common_args: "-o ProxyCommand='ssh -i key-aws-demo.pem -p 22 -W %h:%p -q ec2-user@{{ hostvars['bastion']['ansible_ssh_host']}}'"

    # NOTE: maybe rsync content from the bastion to the test nodes
 
- name: "Configure the BGP Router VM"
  hosts: bgp
  gather_facts: false
  become: true
  tasks:
#    - name: "Wait For SSH Connectivity"
#      failed_when: false
#      ansible.builtin.wait_for_connection:
#        timeout: 90
#
#    - name: "Wait For SSH Connectivity"
#      failed_when: false
#      ansible.builtin.wait_for_connection:
#        timeout: 90
#
#    - name: "Wait For SSH Connectivity"
#      ansible.builtin.wait_for_connection:
#        timeout: 90

    - name: "Install FRR"
      ansible.builtin.dnf:
        name: frr
        state: present

    - name: "Configure FRR Daemons"
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        search_string: "bgpd=no"
        line: "bgpd=yes"

    - name: "Configure FRR"
      ansible.builtin.copy:
        owner: frr
        group: frr
        mode: "u=rw,g=r,o="
        dest: /etc/frr/frr.conf
        # TODO: TBD but for each AZ, the router id and two tor peers should change but the rest of alpha/beta should stay the same
        content: |
            hostname {{ aws_private_dns_name }}
            ip prefix-list ACCEPT_CLUSTERS seq 5 permit 10.1.0.0/16 le 32
            ip prefix-list ACCEPT_CLUSTERS seq 10 permit 10.2.0.0/16 le 32
            !
            router bgp 65000
             bgp router-id 10.0.0.69
             bgp bestpath as-path multipath-relax
             ! todo/ex. neighbor 10.0.32.96 remote-as 65000
             ! todo/ex. neighbor 10.0.64.96 remote-as 65000
             neighbor 10.1.0.96 remote-as 65001
             neighbor 10.1.32.96 remote-as 65001
             neighbor 10.1.64.96 remote-as 65001
             neighbor 10.2.0.96 remote-as 65002
             neighbor 10.2.32.96 remote-as 65002
             neighbor 10.2.64.96 remote-as 65002
             ! TEST
             neighbor 10.1.18.20 remote-as 65001
             neighbor 10.1.18.20 ebgp-multihop 255
             ! TEST
             address-family ipv4 unicast
              neighbor 10.1.0.96 soft-reconfiguration inbound
              neighbor 10.1.0.96 route-map ACCEPT_CLUSTERS in
              !
              neighbor 10.1.32.96 soft-reconfiguration inbound
              neighbor 10.1.32.96 route-map ACCEPT_CLUSTERS in
              !
              neighbor 10.1.64.96 soft-reconfiguration inbound
              neighbor 10.1.64.96 route-map ACCEPT_CLUSTERS in
              !
              neighbor 10.2.0.96 soft-reconfiguration inbound
              neighbor 10.2.32.96 route-map ACCEPT_CLUSTERS in
              !
              neighbor 10.2.32.96 soft-reconfiguration inbound
              neighbor 10.2.32.96 route-map ACCEPT_CLUSTERS in
              !
              neighbor 10.2.64.96 soft-reconfiguration inbound
              neighbor 10.2.64.96 route-map ACCEPT_CLUSTERS in
              ! TEST
              neighbor 10.1.18.20 soft-reconfiguration inbound
              neighbor 10.1.18.20 route-map ACCEPT_CLUSTERS in
              ! TEST
              maximum-paths 4
             exit-address-family
            exit
            !
            route-map ACCEPT_CLUSTERS permit 10
             match ip address prefix-list ACCEPT_CLUSTERS
            exit

    - name: "Enable and Restart the FRR Service"
      ansible.builtin.service:
        name: frr
        enabled: true
        state: restarted
