# Always add a listener as the listener creates the application service
---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: {{ printf "%s-%s-listener" .Values.cluster .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  routingKey: {{ .Values.name }}
  host: {{ .Values.name }}
  port: 8080
  type: tcp
...

# If the application is deployed locally to the cluster, a connector is required for incoming cross-cluster traffic and the site needs linkAccess (default, route, etc)
{{ if .Values.local }}
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  generation: 1
  name: {{ printf "%s-%s" .Values.cluster .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  port: 8080
  routingKey: {{ .Values.name }}
  selector: app={{ .Values.name }}
  type: tcp
...
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: {{ printf "%s-%s" .Values.cluster .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  linkAccess: route 
...

# If the application is not deployed locally, a connector is not required and the site needs linkAccess disabled
{{ else }}
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: {{ printf "%s-%s" .Values.cluster .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  linkAccess: none 
...
{{ end }}
