---
clusters:
  vars:
    sandbox_domain: "{{ lookup('ansible.builtin.env', 'AWS_PROFILE') | default('sandboxXYZ') }}.opentlc.com"
    domain_path: "{{ playbook_dir }}/ocp/{{ sandbox_domain }}"
  hosts:
    alpha:
      install_config_path: "{{ domain_path }}/alpha.install-config.yaml"
      install_path: "{{ domain_path }}/alpha"
      kubeconfig_path: "{{ domain_path }}/alpha/auth/kubeconfig"
      username: admin
      argo_path: "{{ domain_path }}/alpha/argo"
    beta:
      install_config_path: "{{ domain_path }}/beta.install-config.yaml"
      install_path: "{{ domain_path }}/beta"
      kubeconfig_path: "{{ domain_path }}/beta/auth/kubeconfig"
      username: admin
      argo_path: "{{ domain_path }}/beta/argo"

