{{- range $.Values.metallb.static_ipaddresspools }}
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ .name }}-advert
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  aggregationLength: 32
  aggregationLengthV6: 128
  ipAddressPools:
  - {{ .name }}
  peers:
  {{- range $.Values.metallb.bgppeers }}
  - {{ .name }}
  {{- end }}
  nodeSelectors:
    - matchLabels:
        {{ .health_label | quote }}: "true"
{{- end }}
