apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-skupper-healthchecks
  namespace: metallb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-skupper-healthchecks-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["skupper.io"]
  resources: ["sites"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-skupper-healthchecks-rolebinding
  namespace: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-skupper-healthchecks-role
subjects:
- kind: ServiceAccount
  name: metallb-skupper-healthchecks
  namespace: metallb-system

# TODO: Variablize all healthcheck labels/conditions - currently hardcoded

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-skupper-healthchecks-script
  namespace: metallb-system
data:
  "healthcheck.sh": |-
    #!/bin/bash

    STATE_SHARED=""
    STATE_APP1=""
    STATE_APP2=""
    STATE_APP3=""

    while true; do

      APP1=$(oc get site -n app1 app1 -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
      APP2=$(oc get site -n app2 app2 -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
      APP3=$(oc get site -n app3 app3 -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')

      if [ "$APP1" == "True" ] && [ "$APP2" == "True" ] && [ "$APP3" == "True" ]; then
        if [ "$STATE_SHARED" == "GOOD" ]; then
          echo .;
        else
          echo "SHARED HEALTHCHECK PASSED - REMOVING TAINT FROM WORKER NODES ..."
          oc label nodes -l node-role.kubernetes.io/worker network.status/shared-anycast=true --overwrite | grep -ve ".* not labeled";
          STATE_SHARED="GOOD";
        fi
      else
        echo "{ \"status\": { \"APP1\": \"$APP1\", \"APP2\": \"$APP2\", \"APP3\": \"$APP3\" } }";
        echo "SHARED HEALTHCHECK FAILED - TAINTING WORKER NODES ...";
        oc label nodes -l node-role.kubernetes.io/worker network.status/shared-anycast=false --overwrite | grep -ve ".*not labeled";
        STATE_SHARED="BAD";
      fi

      if [ "$APP1" == "True" ]; then
        if [ "$STATE_APP1" == "GOOD" ]; then
          echo .;
        else
          echo "DEDICATED APP1 HEALTHCHECK PASSED - REMOVING TAINT FROM WORKER NODES ..."
          oc label nodes -l node-role.kubernetes.io/worker network.status/app1-anycast=true --overwrite | grep -ve ".* not labeled";
          STATE_APP1="GOOD";
        fi
      else
        echo "{ \"status\": { \"APP1\": \"$APP1\" } }";
        echo "DEDICATED APP1 HEALTHCHECK FAILED - TAINTING WORKER NODES ...";
        oc label nodes -l node-role.kubernetes.io/worker network.status/app1-anycast=false --overwrite | grep -ve ".*not labeled";
        STATE_APP1="BAD";
      fi

      if [ "$APP2" == "True" ]; then
        if [ "$STATE_APP2" == "GOOD" ]; then
          echo .;
        else
          echo "DEDICATED APP2 HEALTHCHECK PASSED - REMOVING TAINT FROM WORKER NODES ..."
          oc label nodes -l node-role.kubernetes.io/worker network.status/app2-anycast=true --overwrite | grep -ve ".* not labeled";
          STATE_APP2="GOOD";
        fi
      else
        echo "{ \"status\": { \"APP2\": \"$APP2\" } }";
        echo "DEDICATED APP2 HEALTHCHECK FAILED - TAINTING WORKER NODES ...";
        oc label nodes -l node-role.kubernetes.io/worker network.status/app2-anycast=false --overwrite | grep -ve ".*not labeled";
        STATE_APP2="BAD";
      fi

      if [ "$APP3" == "True" ]; then
        if [ "$STATE_APP3" == "GOOD" ]; then
          echo .;
        else
          echo "DEDICATED APP3 HEALTHCHECK PASSED - REMOVING TAINT FROM WORKER NODES ..."
          oc label nodes -l node-role.kubernetes.io/worker network.status/app3-anycast=true --overwrite | grep -ve ".* not labeled";
          STATE_APP3="GOOD";
        fi
      else
        echo "{ \"status\": { \"APP3\": \"$APP3\" } }";
        echo "DEDICATED APP3 HEALTHCHECK FAILED - TAINTING WORKER NODES ...";
        oc label nodes -l node-role.kubernetes.io/worker network.status/app3-anycast=false --overwrite | grep -ve ".*not labeled";
        STATE_APP3="BAD";
      fi

      sleep 1;

    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-skupper-healthchecks
  namespace: metallb-system
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: metallb-skupper-healthchecks
  template:
    metadata:
      labels:
        app: metallb-skupper-healthchecks
      name: metallb-skupper-healthchecks
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: metallb-skupper-healthchecks
      containers:
        - name: healthcheck
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          command:
            - /bin/bash
          args:
            - -c
            - /app/healthcheck.sh
          volumeMounts:
            - mountPath: /app
              name: healthcheck-script
      volumes:
        - name: healthcheck-script
          configMap:
            defaultMode: 493
            name: metallb-skupper-healthchecks-script

