---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: app2
  namespace: app2
spec:
  enable: false
  linkAccess: none
...

---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: app2
  namespace: app2
spec:
  routingKey: app2
  host: app2
  port: 8080
  type: tcp
...

