# TODO: fix matchLabels
# TODO: if additional routers deployed, add peering with the bgp routers in az2 (10.1.32.96)/az3(10.1.64.96)
apiVersion: v1
kind: List
items:
# us-east-2a
- apiVersion: metallb.io/v1beta2
  kind: BGPPeer
  metadata:
    name: beta-us-east-2a
    namespace: metallb-system
  spec:
    disableMP: false
    myASN: 65002
    peerASN: 65000
    peerAddress: 10.0.0.96
    peerPort: 179
    routerID: 10.2.0.96
    sourceAddress: 10.2.0.96
    nodeSelectors:
      - matchLabels:
          kubernetes.io/hostname: beta-smj8q-worker-us-east-2a-p4gtx

- apiVersion: metallb.io/v1beta2
  kind: BGPPeer
  metadata:
    name: beta-us-east-2b
    namespace: metallb-system
  spec:
    disableMP: false
    myASN: 65002
    peerASN: 65000
    peerAddress: 10.0.0.96
    peerPort: 179
    routerID: 10.2.32.96
    sourceAddress: 10.2.32.96
    nodeSelectors:
      - matchLabels:
          kubernetes.io/hostname: beta-smj8q-worker-us-east-2a-khkm7

- apiVersion: metallb.io/v1beta2
  kind: BGPPeer
  metadata:
    name: beta-us-east-2c
    namespace: metallb-system
  spec:
    disableMP: false
    myASN: 65002
    peerASN: 65000
    peerAddress: 10.0.0.96
    peerPort: 179
    routerID: 10.2.64.96
    sourceAddress: 10.2.64.96
    nodeSelectors:
      - matchLabels:
          kubernetes.io/hostname: beta-smj8q-worker-us-east-2a-n6rkv

# us-east-2b
# TBD

# us-east-2c
# TBD
