---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: app1
  namespace: app1
spec:
  enable: false 
  linkAccess: none
...

---
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: app1
  namespace: app1
spec:
  routingKey: app1
  host: app1
  port: 8080
  type: tcp
...

